# Generated by Django 5.1.6 on 2025-02-07 12:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepayment',
            name='balance',
        ),
        migrations.AddField(
            model_name='feepayment',
            name='payment_mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Cash', 'Cash')], default='online', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feepayment',
            name='transaction_id',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 3, 9)),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='semester',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='semester',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Due',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_split_payment', models.BooleanField(default=False)),
                ('paid_status', models.BooleanField(default=False)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
