# Generated by Django 5.1.6 on 2025-02-07 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0003_remove_feepayment_balance_feepayment_payment_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('Online', 'Online'), ('Cash', 'Cash')], max_length=50)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('date_completed', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
