# Generated by Django 5.1.6 on 2025-02-07 12:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0004_completedue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='due',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues', to='hostelapp.feestructure'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='hostelapp.feestructure'),
        ),
    ]
