# Generated by Django 5.1.4 on 2025-02-07 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0005_alter_due_semester_alter_profile_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedue',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelapp.feestructure'),
        ),
        migrations.AlterField(
            model_name='due',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues', to=settings.AUTH_USER_MODEL),
        ),
    ]
