# Generated by Django 5.1.4 on 2025-02-07 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0006_alter_completedue_semester_alter_due_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
