# Generated by Django 5.1.4 on 2025-02-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0008_rename_roll_no_user_user_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='roll_no',
            field=models.CharField(default=1000, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
