# Generated by Django 5.1.4 on 2025-02-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0011_remove_user_username_user_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roll_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
