# Generated by Django 5.1.4 on 2025-02-07 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0014_alter_user_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
