# Generated by Django 5.1.4 on 2025-02-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0016_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bed',
            field=models.CharField(blank=True, help_text='Bed identifier (e.g., B)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hostel',
            field=models.CharField(blank=True, help_text='Hostel or Block details (e.g., Block A)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='room_number',
            field=models.CharField(blank=True, help_text='Room number (e.g., 102)', max_length=10, null=True),
        ),
    ]
