# Generated by Django 5.1.4 on 2025-02-09 09:23

import hostelapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0017_profile_bed_profile_hostel_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload your profile picture', null=True, upload_to=hostelapp.models.profile_picture_upload_to),
        ),
    ]
