# Generated by Django 5.1.4 on 2025-02-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0018_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='due',
            name='semester_code',
            field=models.IntegerField(default=1),
        ),
    ]
